### ISSUE TITLE
original() function declaration issue

### ISSUE THREAD

**Issue by alexkaskasoli** [dc-js/dc.graph.js#37]
Hi Gordon,

I've been meaning to give your dc.graph.js library a try for some time. I checked out your example in Firefox and get this issue on line 1295:

`SyntaxError: in strict mode code, functions may be declared only at top level or immediately within another function`

I'm completely new to Javascript, but the issue seems to be that you're declaring the the `original()` function in an `if` statement.

Works fine in Chrome though, it seems like it's more lax than Firefox.

**Comment by gordonwoodhull** [comment]
Thanks @alexkaskasoli for the report! 

Indeed I haven't tested much on Firefox, or anything but Chrome for that matter. Firefox tends to be the most standards compliant (although Edge may be taking that role) so it's an important place to test.
